name: Sonatype Workflow
on: push
jobs:
  sonatype-cli:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
    
    #setup Sonatype CLI
      - name: Setup Sonatype CLI
        uses: sonatype/actions/setup-iq-cli@v1
        with:
          iq-cli-version: 1.179.0-01

      - name: Download pip Deps
        run: | 
          mkdir pip-modules
          pip download -r requirements.txt -d pip-modules
        
      # Perform an evaluation 
      - name: Run evaluate action
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: https://iq.ajoanes.ngrok.io/
          username: ${{ secrets.LIFECYCLE_USERNAME }}
          password: ${{ secrets.LIFECYCLE_PASSWORD }}
          application-id: pygoat__ajoanes98
          scan-targets: 'pip-modules'
        
      # Fetch the SBOM file associated with the evaluation
      # - name: Fetch SBOM
      #   uses: sonatype/actions/fetch-sbom@v1
      #   if: ( success() || failure() ) && steps.evaluate.outputs.scan-id 
      #   with:
      #     iq-server-url: https://iq.ajoanes.ngrok.io/
      #     username: ${{ secrets.LIFECYCLE_USERNAME }}
      #     password: ${{ secrets.LIFECYCLE_PASSWORD }}
      #     application-id: pygoat__ajoanes98
      #     scan-id: ${{ steps.evaluate.outputs.scan-id }}
      #     sbom-standard: cyclonedx
      #     sbom-version: 1.5
      #     sbom-format: json
      #     artifact-name: lifecycle-app-sbom.json
