name: Pull, Build, and Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies through Nexus proxy repository
    - name: Install dependencies
      env:
        HTTPS_PROXY: https://repo.ajoanes.ngrok.io/repository/pypi-proxy/
        username: admin
        password: admin1234
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build the Python project
    # - name: Build the project
    #   run: |
    #     python setup.py sdist bdist_wheel

    # Step 5: Run Sonatype Nexus IQ Scan
    - name: Run Nexus IQ Scan
      env:
        NEXUS_IQ_URL: https://iq.ajoanes.ngrok.io/
        NEXUS_IQ_APPLICATION: python-ci
        NEXUS_IQ_USER: admin
        NEXUS_IQ_TOKEN: iqAj610298!
      run: |
        curl -O https://download.sonatype.com/clm/scanner/latest/nexus-iq-cli.jar
        java -jar nexus-iq-cli.jar \
          -i $NEXUS_IQ_APPLICATION \
          -s $NEXUS_IQ_URL \
          -u $NEXUS_IQ_USER \
          -p $NEXUS_IQ_TOKEN \
          --stage build \
          target/
